# Generated by Django 5.1.4 on 2025-06-15 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermodel',
            name='is_pulbic_profile',
        ),
        migrations.AddField(
            model_name='usermodel',
            name='is_public_profile',
            field=models.BooleanField(default=True, verbose_name='возможность просмотра профиля другими игроками'),
        ),
    ]
