# Generated by Django 5.1.4 on 2025-11-24 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_usermodel_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='steamid64',
            field=models.CharField(default=1, max_length=32, unique=True, verbose_name='steamid64'),
            preserve_default=False,
        ),
    ]
