# Generated by Django 5.1.4 on 2025-11-24 21:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_usermodel_steamid64'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermodel',
            name='password',
        ),
    ]
