# Generated by Django 5.1.4 on 2025-06-07 12:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='generalnewsmodel',
            options={'verbose_name': 'общая новость сайта', 'verbose_name_plural': 'общие новости сайта'},
        ),
        migrations.AlterField(
            model_name='generalnewsmodel',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='general_news_by_user', to=settings.AUTH_USER_MODEL, verbose_name='автор'),
        ),
    ]
