# Generated by Django 5.1.4 on 2025-06-07 11:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teams', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members_by_user', to=settings.AUTH_USER_MODEL, verbose_name='пользователь'),
        ),
        migrations.AddField(
            model_name='teammodel',
            name='leader',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teams_by_leader', to=settings.AUTH_USER_MODEL, verbose_name='лидер'),
        ),
        migrations.AddField(
            model_name='teammodel',
            name='members',
            field=models.ManyToManyField(related_name='team_by_member', to='teams.member'),
        ),
    ]
