# Generated by Django 5.1.4 on 2025-06-14 16:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InvitationToTeamModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='дата и время отправки')),
                ('status', models.CharField(choices=[('pending', 'Ожидается'), ('accepted', 'Принята'), ('rejected', 'Отклонена'), ('expired', 'Просрочена')], default='pending', max_length=32, verbose_name='статус')),
                ('invited_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='пользователь')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teams.teammodel', verbose_name='команда')),
            ],
            options={
                'verbose_name': 'заявка команды на участие в турнире',
                'verbose_name_plural': 'заявки команды на участие в турнире',
            },
        ),
    ]
