# Generated by Django 5.1.4 on 2025-06-22 10:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0003_invitationtoteammodel'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MemberModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='дата и время создания')),
                ('role_name', models.CharField(max_length=255, verbose_name='название роли участника')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members_by_user', to=settings.AUTH_USER_MODEL, verbose_name='пользователь')),
            ],
            options={
                'verbose_name': 'участник',
                'verbose_name_plural': 'участники',
            },
        ),
        migrations.AlterField(
            model_name='teammodel',
            name='members',
            field=models.ManyToManyField(related_name='team_by_member', to='teams.membermodel'),
        ),
        migrations.DeleteModel(
            name='Member',
        ),
    ]
