# Generated by Django 5.1.4 on 2025-08-11 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0004_membermodel_alter_teammodel_members_delete_member'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membermodel',
            name='role_name',
            field=models.CharField(max_length=32, verbose_name='название роли участника'),
        ),
    ]
