# Generated by Django 5.1.4 on 2025-09-07 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0005_alter_membermodel_role_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='membermodel',
            old_name='role_name',
            new_name='role',
        ),
    ]
