# Generated by Django 5.1.4 on 2025-10-17 20:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0006_rename_role_name_membermodel_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teammodel',
            name='members',
        ),
        migrations.AddField(
            model_name='membermodel',
            name='team_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='members_by_team', to='teams.teammodel', verbose_name='команда'),
            preserve_default=False,
        ),
    ]
