# Generated by Django 5.1.4 on 2025-10-17 20:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0007_remove_teammodel_members_membermodel_team_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='membermodel',
            old_name='team_id',
            new_name='team',
        ),
    ]
