# Generated by Django 5.1.4 on 2025-06-07 11:45

import django.core.validators
import mdeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EventForTimeTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='название')),
                ('description', mdeditor.fields.MDTextField(default='', verbose_name='описание')),
                ('start_datetime', models.DateTimeField(verbose_name='дата и время начала')),
                ('end_datetime', models.DateTimeField(verbose_name='дата и время окончания')),
            ],
            options={
                'verbose_name': 'событие для расписания турнира',
                'verbose_name_plural': 'события для расписания турнира',
            },
        ),
        migrations.CreateModel(
            name='TournamentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='название турнира')),
                ('description', mdeditor.fields.MDTextField(default='', verbose_name='описание')),
                ('rules', mdeditor.fields.MDTextField(default='', verbose_name='правила')),
                ('count_of_members_in_team', models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(32)], verbose_name='количество участников в одной команде')),
                ('count_of_teams', models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)], verbose_name='количество команд')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='дата и время создания')),
                ('start_datetime', models.DateTimeField(verbose_name='дата и время начала')),
                ('end_datetime', models.DateTimeField(verbose_name='дата и время начала')),
                ('is_closed_for_requests', models.BooleanField(default=True, verbose_name='можно ли ещё зарегистрироваться')),
            ],
            options={
                'verbose_name': 'турнир',
                'verbose_name_plural': 'турниры',
            },
        ),
    ]
