# Generated by Django 5.1.4 on 2025-06-07 11:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tournaments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='tournamentmodel',
            name='judges',
            field=models.ManyToManyField(blank=True, related_name='tournaments_by_judges', to=settings.AUTH_USER_MODEL, verbose_name='судьи'),
        ),
        migrations.AddField(
            model_name='tournamentmodel',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tournaments_by_owner', to=settings.AUTH_USER_MODEL, verbose_name='владелец'),
        ),
        migrations.AddField(
            model_name='eventfortimetable',
            name='tournament',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tournament_by_timetable_events', to='tournaments.tournamentmodel', verbose_name='турнир'),
        ),
    ]
