# Generated by Django 5.1.4 on 2025-06-07 11:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournamentmodel',
            name='end_for_requests_datetime',
            field=models.DateTimeField(default=datetime.datetime(2025, 6, 7, 23, 59, 59), verbose_name='дата и время окончания регистрации'),
            preserve_default=False,
        ),
    ]
