# Generated by Django 5.1.4 on 2025-06-07 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0003_tournamentmodel_end_for_requests_datetime'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tournamentmodel',
            name='end_for_requests_datetime',
        ),
    ]
