# Generated by Django 5.1.4 on 2025-06-07 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0004_remove_tournamentmodel_end_for_requests_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournamentmodel',
            name='is_closed_for_requests',
            field=models.BooleanField(default=False, verbose_name='можно ли ещё зарегистрироваться'),
        ),
    ]
