# Generated by Django 5.1.4 on 2025-06-07 12:43

import django.db.models.deletion
import mdeditor.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0005_alter_tournamentmodel_is_closed_for_requests'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TournamentNews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=127, verbose_name='заголовок')),
                ('content', mdeditor.fields.MDTextField(verbose_name='содержимое')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='дата и время создания')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tournament_news_by_user', to=settings.AUTH_USER_MODEL, verbose_name='автор')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='news_by_tournament', to='tournaments.tournamentmodel', verbose_name='турнир')),
            ],
            options={
                'verbose_name': 'новость турнира',
                'verbose_name_plural': 'новости турниров',
            },
        ),
    ]
