# Generated by Django 5.1.4 on 2025-06-14 16:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0003_invitationtoteammodel'),
        ('tournaments', '0006_tournamentnews'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestTeamForTournamentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='дата и время отправки')),
                ('status', models.CharField(choices=[('pending', 'Ожидается'), ('accepted', 'Принята'), ('rejected', 'Отклонена'), ('expired', 'Просрочена')], default='pending', max_length=32, verbose_name='статус')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teams.teammodel', verbose_name='команда')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tournaments.tournamentmodel', verbose_name='турнир')),
            ],
            options={
                'verbose_name': 'заявка команды на участие в турнире',
                'verbose_name_plural': 'заявки команды на участие в турнире',
            },
        ),
    ]
