# Generated by Django 5.1.4 on 2025-10-19 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0007_requestteamfortournamentmodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tournamentmodel',
            name='count_of_members_in_team',
        ),
        migrations.RemoveField(
            model_name='tournamentmodel',
            name='count_of_teams',
        ),
        migrations.RemoveField(
            model_name='tournamentmodel',
            name='end_datetime',
        ),
        migrations.RemoveField(
            model_name='tournamentmodel',
            name='start_datetime',
        ),
        migrations.AlterField(
            model_name='tournamentmodel',
            name='is_closed_for_requests',
            field=models.BooleanField(default=False, verbose_name='можно ли ещё подать заявку на участие'),
        ),
    ]
