# Generated by Django 5.1.4 on 2025-10-25 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0008_rename_team_id_membermodel_team'),
        ('tournaments', '0008_remove_tournamentmodel_count_of_members_in_team_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournamentmodel',
            name='team_members',
            field=models.ManyToManyField(related_name='tournaments', to='teams.teammodel'),
        ),
    ]
