# Generated by Django 5.1.4 on 2025-10-29 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0009_tournamentmodel_team_members'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournamentmodel',
            name='is_closed_for_requests',
            field=models.BooleanField(default=False, verbose_name='Закрыт ли для подачи заявок'),
        ),
    ]
