# Generated by Django 5.1.4 on 2025-10-31 20:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0008_rename_team_id_membermodel_team'),
        ('tournaments', '0010_alter_tournamentmodel_is_closed_for_requests'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tournamentmodel',
            name='judges',
        ),
        migrations.CreateModel(
            name='BattleModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='дата и время создания')),
                ('status', models.CharField(choices=[('win_first', 'Победа первой команды'), ('win_second', 'Победа второй команды'), ('draw', 'Ничья'), ('soon', 'Ещё не был проведён'), ('problem', 'Не состоялса по техническим причинам')], max_length=64, verbose_name='статус проведения')),
                ('start_datetime', models.DateTimeField(verbose_name='дата и время начала')),
                ('proof', models.TextField(default='', verbose_name='доказательство')),
                ('fisrt_team', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='battles_team_first', to='teams.teammodel', verbose_name='первая команда')),
                ('judge', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='battles_by_judge', to=settings.AUTH_USER_MODEL, verbose_name='судья отвечающий')),
                ('second_team', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='battles_team_second', to='teams.teammodel', verbose_name='вторая команда')),
            ],
            options={
                'verbose_name': 'сражение',
                'verbose_name_plural': 'сражения',
            },
        ),
        migrations.CreateModel(
            name='JudgeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='judges_by_tournament', to='tournaments.tournamentmodel', verbose_name='турнир')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='judges_by_user', to=settings.AUTH_USER_MODEL, verbose_name='пользователь')),
            ],
            options={
                'verbose_name': 'судья',
                'verbose_name_plural': 'судьи',
            },
        ),
    ]
