# Generated by Django 5.1.4 on 2025-11-09 18:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0008_rename_team_id_membermodel_team'),
        ('tournaments', '0012_tournamentmodel_judges_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='battlemodel',
            name='fisrt_team',
        ),
        migrations.AddField(
            model_name='battlemodel',
            name='first_team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='battles_team_first', to='teams.teammodel', verbose_name='первая команда'),
        ),
    ]
