# Generated by Django 5.1.4 on 2025-11-09 19:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0013_remove_battlemodel_fisrt_team_battlemodel_first_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='battlemodel',
            name='tournament',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='battles_by_tournament', to='tournaments.tournamentmodel', verbose_name='турнир в котором будет проведено сражение'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='battlemodel',
            name='status',
            field=models.CharField(choices=[('win_first', 'Победа первой команды'), ('win_second', 'Победа второй команды'), ('draw', 'Ничья'), ('soon', 'Ещё не был проведён'), ('problem', 'Не состоялса по техническим причинам')], default='soon', max_length=64, verbose_name='статус проведения'),
        ),
    ]
