# Generated by Django 5.1.4 on 2025-11-14 20:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0008_rename_team_id_membermodel_team'),
        ('tournaments', '0014_battlemodel_tournament_alter_battlemodel_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tournamentmodel',
            name='team_members',
        ),
        migrations.CreateModel(
            name='MembershipTournamentTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=32, verbose_name='статус команды на турнире')),
                ('team', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='memberships_by_team', to='teams.teammodel', verbose_name='команда')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships_by_tournament', to='teams.teammodel', verbose_name='команда')),
            ],
            options={
                'verbose_name': 'участие команды в турнире',
                'verbose_name_plural': 'участие команды в турнире',
            },
        ),
    ]
