# Generated by Django 5.1.4 on 2025-11-14 20:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0015_remove_tournamentmodel_team_members_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membershiptournamentteam',
            name='tournament',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships_by_tournament', to='tournaments.tournamentmodel', verbose_name='команда'),
        ),
    ]
