# Generated by Django 5.1.4 on 2025-11-14 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0008_rename_team_id_membermodel_team'),
        ('tournaments', '0016_alter_membershiptournamentteam_tournament'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournamentmodel',
            name='team_members',
            field=models.ManyToManyField(related_name='tournaments', to='teams.teammodel', verbose_name='команды участники'),
        ),
        migrations.DeleteModel(
            name='MembershipTournamentTeam',
        ),
    ]
