# Generated by Django 5.1.4 on 2025-11-21 21:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0017_tournamentmodel_team_members_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TournamentNews',
            new_name='TournamentNewsModel',
        ),
        migrations.AlterField(
            model_name='requestteamfortournamentmodel',
            name='status',
            field=models.CharField(choices=[('pending', 'Ожидается'), ('accepted', 'Принята'), ('rejected', 'Отклонена')], default='pending', max_length=32, verbose_name='статус'),
        ),
    ]
