# Generated by Django 5.1.4 on 2025-11-26 21:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0008_rename_team_id_membermodel_team'),
        ('tournaments', '0019_alter_tournamentnewsmodel_author'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournamentmodel',
            name='judges',
            field=models.ManyToManyField(blank=True, related_name='tournaments_where_judge', to=settings.AUTH_USER_MODEL, verbose_name='судьи'),
        ),
        migrations.AlterField(
            model_name='tournamentmodel',
            name='team_members',
            field=models.ManyToManyField(blank=True, related_name='tournaments', to='teams.teammodel', verbose_name='команды участники'),
        ),
    ]
