# Generated by Django 5.1.4 on 2025-06-07 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BattleModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='дата и время создания')),
                ('status', models.CharField(choices=[('win_first', 'Победа первой команды'), ('win_second', 'Победа второй команды'), ('draw', 'Ничья'), ('soon', 'Ещё не был проведён'), ('problem', 'Не состоялса по техническим причинам')], max_length=64, verbose_name='статус проведения')),
                ('start_datetime', models.DateTimeField(verbose_name='дата и время начала')),
                ('proof', models.TextField(default='', verbose_name='доказательство')),
            ],
            options={
                'verbose_name': 'сражение',
                'verbose_name_plural': 'сражения',
            },
        ),
    ]
