# Generated by Django 5.1.4 on 2025-06-07 11:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('battles', '0001_initial'),
        ('teams', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='battlemodel',
            name='judges',
            field=models.ManyToManyField(blank=True, related_name='battles_by_judge', to=settings.AUTH_USER_MODEL, verbose_name='судьи'),
        ),
        migrations.AddField(
            model_name='battlemodel',
            name='team_first',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='battles_team_first', to='teams.teammodel', verbose_name='первая команда'),
        ),
        migrations.AddField(
            model_name='battlemodel',
            name='team_second',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='battles_team_second', to='teams.teammodel', verbose_name='вторая команда'),
        ),
    ]
